# Fortran compiler
F77 = gfortran-mp-14
# Flags
OPT = -g

# Build everything: all *.xOg plus selected *.e tools
SRCS_XOG = $(filter-out dex_no_gaia.F xym2mat_new.F,$(sort $(wildcard *.F) $(wildcard *.f)))
EXECUTABLES_XOG = $(addsuffix .xOg,$(basename $(SRCS_XOG)))

all: $(EXECUTABLES_XOG) dex_no_gaia.e xym2mat_new.e

dex_no_gaia.e: dex_no_gaia.F
	$(F77) $(OPT) $< -o $@

xym2mat_new.e: xym2mat_new.F
	$(F77) $(OPT) $< -o $@

xogs: $(EXECUTABLES_XOG)

%.xOg: %.F
	$(F77) $(OPT) $< -o $@

%.xOg: %.f
	$(F77) $(OPT) -cpp $< -o $@

# Convenience targets
dex: dex_no_gaia.e
xym2mat_new: xym2mat_new.e

clean:
	rm -f dex_no_gaia.e xym2mat_new.e $(EXECUTABLES_XOG)