# Fortran compiler
F77 = gfortran-mp-14
# Flags
OPT = -g

# All .F sources
SRCS = $(wildcard *.F)

# Convert program.F → program.xOg)
EXECUTABLES = $(SRCS:.F=.xOg)

# Default: build all executables
all: $(EXECUTABLES)

# Rule: program.F → program.xOg
%.xOg: %.F
	$(F77) $(OPT) $< -o $@

# Clean everything
clean:
	rm -f *.xOg
